### ISSUE TITLE
ImportError: cannot import name 'EdgeGPT' from 'EdgeGPT' 

### ISSUE THREAD

**Issue by G-LJDS2022** [xbzstudio/Timeless-Sydney#86]
E:\AI\Timeless-Sydney\Timeless-Sydney-8.16>python main.py
Traceback (most recent call last):
  File "E:\AI\Timeless-Sydney\Timeless-Sydney-8.16\main.py", line 5, in <module>
    from EdgeGPT import EdgeGPT as gpt
ImportError: cannot import name 'EdgeGPT' from 'EdgeGPT' (D:\Python\Lib\site-packages\EdgeGPT.py)

**Comment by G-LJDS2022** [comment]
感觉是EdgeGPT版本的原因，请问使用的是哪个版本的EdgeGPT？

**Comment by xbzstudio** [comment]
不是版本问题 是你根本没下载。下载我发布的最新的1.8.1，然后按照流程再弄一遍就可以解决了

**Comment by G-LJDS2022** [comment]
> 不是版本问题 是你根本没下载。下载我发布的最新的1.8.1，然后按照流程再弄一遍就可以解决了

解决了，我直接复制了edgegpt文件夹，替换了原来的文件。我用的是最新的版本。

**Comment by G-LJDS2022** [comment]
估计是edgegpt版本的问题

**Comment by OXERIS** [comment]
> 不是版本问题是你根本没下载。下载我发布的最新的1.8.1，然后按照流程再弄一遍就可以解决了

我也遇到这个报错
Traceback (most recent call last):
  File "C:\Users\thego\Downloads\Timeless-Sydney-TimlessSydney1.8.2\Timeless-Sydney-TimlessSydney1.8.2\main.py", line 5, in <module>
    from EdgeGPT import EdgeGPT as gpt
ImportError: cannot import name 'EdgeGPT' from 'EdgeGPT' (C:\Users\thego\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT.py)
我觉得是不是和我安装的SydneyQt-master冲突了

**Comment by OXERIS** [comment]
> 不是版本问题是你根本没下载。下载我发布的最新的1.8.1，然后按照流程再弄一遍就可以解决了

我下载的是你的最新版本，1.8.2，而且尝试安装依赖时提示全部都已经安装了
C:\Users\thego\Downloads\Timeless-Sydney-TimlessSydney1.8.2\Timeless-Sydney-TimlessSydney1.8.2>pip install -r requirements.txt
Requirement already satisfied: EdgeGPT in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 1)) (0.8.1)
Requirement already satisfied: FastAPI in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 2)) (0.101.1)
Requirement already satisfied: aiohttp in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 3)) (3.8.5)
Requirement already satisfied: uvicorn in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 4)) (0.23.2)
Requirement already satisfied: python-multipart in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 5)) (0.0.6)
Requirement already satisfied: httpx[socks]>=0.24.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from EdgeGPT->-r requirements.txt (line 1)) (0.24.1)
Requirement already satisfied: websockets in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from EdgeGPT->-r requirements.txt (line 1)) (11.0.3)
Requirement already satisfied: rich in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from EdgeGPT->-r requirements.txt (line 1)) (13.5.2)
Requirement already satisfied: certifi in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from EdgeGPT->-r requirements.txt (line 1)) (2022.12.7)
Requirement already satisfied: prompt-toolkit in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from EdgeGPT->-r requirements.txt (line 1)) (3.0.39)
Requirement already satisfied: requests in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from EdgeGPT->-r requirements.txt (line 1)) (2.28.2)
Requirement already satisfied: aiofiles in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from EdgeGPT->-r requirements.txt (line 1)) (23.2.1)
Requirement already satisfied: BingImageCreator>=0.3.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from EdgeGPT->-r requirements.txt (line 1)) (0.5.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from FastAPI->-r requirements.txt (line 2)) (2.2.0)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from FastAPI->-r requirements.txt (line 2)) (0.27.0)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from FastAPI->-r requirements.txt (line 2)) (4.7.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->-r requirements.txt (line 3)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->-r requirements.txt (line 3)) (3.0.1)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->-r requirements.txt (line 3)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->-r requirements.txt (line 3)) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->-r requirements.txt (line 3)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->-r requirements.txt (line 3)) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from aiohttp->-r requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: click>=7.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from uvicorn->-r requirements.txt (line 4)) (8.1.7)
Requirement already satisfied: h11>=0.8 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from uvicorn->-r requirements.txt (line 4)) (0.14.0)
Requirement already satisfied: regex in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from BingImageCreator>=0.3.0->EdgeGPT->-r requirements.txt (line 1)) (2023.8.8)
Requirement already satisfied: colorama in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from click>=7.0->uvicorn->-r requirements.txt (line 4)) (0.4.6)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT->-r requirements.txt (line 1)) (0.17.3)
Requirement already satisfied: idna in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: sniffio in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: socksio==1.* in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT->-r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->FastAPI->-r requirements.txt (line 2)) (0.5.0)
Requirement already satisfied: pydantic-core==2.6.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->FastAPI->-r requirements.txt (line 2)) (2.6.0)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from starlette<0.28.0,>=0.27.0->FastAPI->-r requirements.txt (line 2)) (3.7.1)
Requirement already satisfied: wcwidth in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from prompt-toolkit->EdgeGPT->-r requirements.txt (line 1)) (0.2.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from requests->EdgeGPT->-r requirements.txt (line 1)) (1.26.14)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from rich->EdgeGPT->-r requirements.txt (line 1)) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from rich->EdgeGPT->-r requirements.txt (line 1)) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\thego\appdata\local\programs\python\python311\lib\site-packages (from markdown-it-py>=2.2.0->rich->EdgeGPT->-r requirements.txt (line 1)) (0.1.2)

**Comment by on-in-i** [comment]
> > 不是版本问题 是你根本没下载。下载我发布的最新的1.8.1，然后按照流程再弄一遍就可以解决了
> 
> 解决了，我直接复制了edgegpt文件夹，替换了原来的文件。我用的是最新的版本。

我遇到了同样的问题，请问如何解决呢？具体是复制了哪里的什么文件夹？替换了哪个路径的文件呢？求解答

**Comment by xbzstudio** [comment]
算了 那你们就在输入一次pip install --upgrade EdgeGPT吧，试试这样

**Comment by OXERIS** [comment]
> 算了 那你们就在输入一次pip install --upgrade EdgeGPT吧，试试这样
虽然更新后能成功运行但是
![image](https://github.com/xbzstudio/Timeless-Sydney/assets/18722082/f8989503-3e8d-4591-b1f7-2ff1c1396bf1)

![image](https://github.com/xbzstudio/Timeless-Sydney/assets/18722082/061f1a43-93d7-4351-9d27-3b2ec6dc6fc7)
