### ISSUE TITLE
System：连接丢失

### ISSUE THREAD

**Issue by G-LJDS2022** [xbzstudio/Timeless-Sydney#87]
![image](https://github.com/xbzstudio/Timeless-Sydney/assets/134282368/2b4d4fd7-bc9d-4be5-8102-2630430c1c3b)

**Comment by G-LJDS2022** [comment]
开了全局，但是没开tun模式

**Comment by xbzstudio** [comment]
看看服务端的报错

**Comment by G-LJDS2022** [comment]
> 看看服务端的报错

E:\AI\Timeless-Sydney\Timeless-Sydney-8.16>python main.py
Server Start
Go to http://127.0.0.1:80/ and start to chat!
[32mINFO[0m:     Started server process [[36m5452[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:80[0m (Press CTRL+C to quit)
[32mINFO[0m:     127.0.0.1:58395 - "[1mGET / HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58395 - "[1mGET /static/angular.min.js HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58397 - "[1mGET /static/default.min.css HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58398 - "[1mGET /static/highlight.min.js HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58399 - "[1mGET /static/mdui.min.css HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58400 - "[1mGET /static/marked.min.js HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58395 - "[1mGET /static/main.css HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58395 - "[1mGET /static/mdui.min.js HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58400 - "[1mGET /config/client.js HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58400 - "[1mGET /%7B%7Bmsg.headimg%7D%7D HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:58400 - "[1mGET /fonts/roboto/Roboto-Regular.woff2 HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:58395 - "[1mGET /fonts/roboto/Roboto-Medium.woff2 HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:58399 - "[1mGET /fonts/roboto/Roboto-Bold.woff2 HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     ('127.0.0.1', 58401) - "WebSocket /chat/ws" [accepted]
[32mINFO[0m:     127.0.0.1:58399 - "[1mGET /chat/getTipNames HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     connection open
[32mINFO[0m:     127.0.0.1:58395 - "[1mGET /static/Bing.png HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58400 - "[1mGET /static/Background.jpg HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:58395 - "[1mGET /fonts/roboto/Roboto-Regular.woff HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:58395 - "[1mGET /fonts/roboto/Roboto-Medium.woff HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:58399 - "[1mGET /fonts/roboto/Roboto-Bold.woff HTTP/1.1[0m" [31m404 Not Found[0m
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Python\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Python\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Python\Lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "D:\Python\Lib\site-packages\starlette\middleware\cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "D:\Python\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\Python\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\Python\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\Python\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\Python\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\Python\Lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "D:\Python\Lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "D:\Python\Lib\site-packages\fastapi\routing.py", line 324, in app
    await dependant.call(**values)
  File "E:\AI\Timeless-Sydney\Timeless-Sydney-8.16\main.py", line 62, in wsStream
    chatbot = await gpt.Chatbot.create(cookies = json.loads(open('./config/cookie.json', 'r', encoding='utf-8').read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 43, in create
    await Conversation.create(self.proxy, cookies=cookies, imgid=imgid),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\EdgeGPT\conversation.py", line 110, in create
    response = await client.get(
               ^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\httpx\_client.py", line 1675, in _send_handling_redirects
    raise TooManyRedirects(
httpx.TooManyRedirects: Exceeded maximum allowed redirects.
[32mINFO[0m:     connection closed

**Comment by G-LJDS2022** [comment]
是80端口被占用导致的问题吗？

**Comment by xbzstudio** [comment]
不是端口问题

**Comment by xbzstudio** [comment]
你上bing官网看看能不能聊天

**Comment by 1234325346** [comment]
up我的检查了全局vpn和防火墙也检查了bing账户 但还是连接丢失 Server Start
Go to http://127.0.0.1:80/ and start to chat!
[32mINFO[0m:     Started server process [[36m16936[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:80[0m (Press CTRL+C to quit)
[32mINFO[0m:     ('127.0.0.1', 51059) - "WebSocket /chat/ws" [accepted]
[32mINFO[0m:     connection open
[32mINFO[0m:     127.0.0.1:51060 - "[1mGET /chat/getTipNames HTTP/1.1[0m" [32m200 OK[0m
Status code: 403

https://www.bing.com/turing/conversation/create
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\routing.py", line 292, in app
    await dependant.call(**values)
  File "E:\Bing-AI\Timeless-Sydney-main\main.py", line 62, in wsStream
    chatbot = await gpt.Chatbot.create(cookies = json.loads(open('./config/cookie.json', 'r', encoding='utf-8').read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\EdgeGPT\EdgeGPT.py", line 42, in create
    await Conversation.create(self.proxy, cookies=cookies),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\EdgeGPT\conversation.py", line 112, in create
    raise Exception("Authentication failed")
Exception: Authentication failed
[31mERROR[0m:    closing handshake failed
Traceback (most recent call last):
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\server.py", line 248, in handler
    await self.close()
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\protocol.py", line 1205, in write_frame
    await self.drain()
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\protocol.py", line 1194, in drain
    await self.ensure_open()
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
[32mINFO[0m:     connection closed
[32mINFO[0m:     ('127.0.0.1', 51065) - "WebSocket /chat/ws" [accepted]
[32mINFO[0m:     connection open
Status code: 403

https://www.bing.com/turing/conversation/create
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fastapi\routing.py", line 292, in app
    await dependant.call(**values)
  File "E:\Bing-AI\Timeless-Sydney-main\main.py", line 62, in wsStream
    chatbot = await gpt.Chatbot.create(cookies = json.loads(open('./config/cookie.json', 'r', encoding='utf-8').read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\EdgeGPT\EdgeGPT.py", line 42, in create
    await Conversation.create(self.proxy, cookies=cookies),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\EdgeGPT\conversation.py", line 112, in create
    raise Exception("Authentication failed")
Exception: Authentication failed
[31mERROR[0m:    closing handshake failed
Traceback (most recent call last):
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\server.py", line 248, in handler
    await self.close()
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\protocol.py", line 766, in close
    await self.write_close_frame(Close(code, reason))
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\protocol.py", line 1232, in write_close_frame
    await self.write_frame(True, OP_CLOSE, data, _state=State.CLOSING)
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\protocol.py", line 1205, in write_frame
    await self.drain()
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\protocol.py", line 1194, in drain
    await self.ensure_open()
  File "C:\Users\asus-pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\legacy\protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1000 (OK); no close frame received
[32mINFO[0m:     connection closed

**Comment by xbzstudio** [comment]
也许你可以换个新cookie，或者换个账号，抑或是你的edgegpt版本过旧

**Comment by xbzstudio** [comment]
破案了 梯子问题，换个节点或者换个vpn

**Comment by xiaoweige1** [comment]
我的也是这个问题
