### ISSUE TITLE
会报错然后关闭连接

### ISSUE THREAD

**Issue by whatmor** [xbzstudio/Timeless-Sydney#91]
INFO:     Started server process [33612]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO:     127.0.0.1:60112 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:60112 - "GET /static/angular.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:60113 - "GET /static/default.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:60114 - "GET /static/main.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:60115 - "GET /static/highlight.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:60116 - "GET /static/mdui.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:60117 - "GET /static/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:60117 - "GET /static/mdui.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:60117 - "GET /config/client.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:60117 - "GET /%7B%7Bmsg.headimg%7D%7D HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:60117 - "GET /fonts/roboto/Roboto-Regular.woff2 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:60116 - "GET /fonts/roboto/Roboto-Medium.woff2 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:60115 - "GET /fonts/roboto/Roboto-Bold.woff2 HTTP/1.1" 404 Not Found
INFO:     ('127.0.0.1', 60118) - "WebSocket /chat/ws" [accepted]
INFO:     connection open
INFO:     127.0.0.1:60115 - "GET /chat/getTipNames HTTP/1.1" 200 OK
INFO:     127.0.0.1:60116 - "GET /static/Bing.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:60117 - "GET /static/Background.jpg HTTP/1.1" 200 OK
INFO:     127.0.0.1:60116 - "GET /fonts/roboto/Roboto-Regular.woff HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:60115 - "GET /fonts/roboto/Roboto-Medium.woff HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:60114 - "GET /fonts/roboto/Roboto-Bold.woff HTTP/1.1" 404 Not Found

**Comment by xbzstudio** [comment]
这有啥问题 这没有任何问题啊

**Comment by whatmor** [comment]
> 这有啥问题 这没有任何问题啊

下面几个不是404吗，会自动关闭链接

**Comment by whatmor** [comment]
> 这有啥问题 这没有任何问题啊

Go to http://127.0.0.1:80/ and start to chat!
INFO:     Started server process [5136]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO:     127.0.0.1:58735 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:58735 - "GET /static/angular.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:58736 - "GET /static/default.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:58738 - "GET /static/main.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:58739 - "GET /static/highlight.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:58740 - "GET /static/marked.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:58741 - "GET /static/mdui.min.css HTTP/1.1" 200 OK
INFO:     127.0.0.1:58741 - "GET /static/mdui.min.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:58740 - "GET /config/client.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:58740 - "GET /%7B%7Bmsg.headimg%7D%7D HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:58740 - "GET /fonts/roboto/Roboto-Regular.woff2 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:58741 - "GET /fonts/roboto/Roboto-Medium.woff2 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:58739 - "GET /fonts/roboto/Roboto-Bold.woff2 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:58739 - "GET /chat/getTipNames HTTP/1.1" 200 OK
INFO:     ('127.0.0.1', 58742) - "WebSocket /chat/ws" [accepted]
INFO:     connection open
INFO:     127.0.0.1:58741 - "GET /static/Bing.png HTTP/1.1" 200 OK
INFO:     127.0.0.1:58739 - "GET /static/Background.jpg HTTP/1.1" 200 OK
INFO:     127.0.0.1:58741 - "GET /fonts/roboto/Roboto-Regular.woff HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:58740 - "GET /fonts/roboto/Roboto-Medium.woff HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:58738 - "GET /fonts/roboto/Roboto-Bold.woff HTTP/1.1" 404 Not Found
Status code: 403

https://www.bing.com/turing/conversation/create
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 324, in app
    await dependant.call(**values)
  File "D:\Timeless-Sydney-main\main.py", line 62, in wsStream
    chatbot = await gpt.Chatbot.create(cookies = json.loads(open('./config/cookie.json', 'r', encoding='utf-8').read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 42, in create
    await Conversation.create(self.proxy, cookies=cookies),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\conversation.py", line 112, in create
    raise Exception("Authentication failed")
Exception: Authentication failed
INFO:     connection closed
INFO:     ('127.0.0.1', 58745) - "WebSocket /chat/ws" [accepted]
INFO:     connection open
Status code: 403

https://www.bing.com/turing/conversation/create
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 324, in app
    await dependant.call(**values)
  File "D:\Timeless-Sydney-main\main.py", line 62, in wsStream
    chatbot = await gpt.Chatbot.create(cookies = json.loads(open('./config/cookie.json', 'r', encoding='utf-8').read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 42, in create
    await Conversation.create(self.proxy, cookies=cookies),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\26249\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\conversation.py", line 112, in create
    raise Exception("Authentication failed")
Exception: Authentication failed
INFO:     connection closed

**Comment by chengdada925** [comment]
D:\BaiduNetdiskDownload\Timeless-Sydney-main>python main.py
Server Start
Go to http://127.0.0.1:80/ and start to chat!
[32mINFO[0m:     Started server process [[36m13152[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:80[0m (Press CTRL+C to quit)
[32mINFO[0m:     127.0.0.1:10289 - "[1mGET / HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10289 - "[1mGET /static/angular.min.js HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10290 - "[1mGET /static/default.min.css HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10291 - "[1mGET /static/main.css HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10292 - "[1mGET /static/highlight.min.js HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10293 - "[1mGET /static/marked.min.js HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10294 - "[1mGET /static/mdui.min.css HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10294 - "[1mGET /config/client.js HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10293 - "[1mGET /static/mdui.min.js HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10293 - "[1mGET /%7B%7Bmsg.headimg%7D%7D HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:10293 - "[1mGET /fonts/roboto/Roboto-Regular.woff2 HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:10294 - "[1mGET /fonts/roboto/Roboto-Medium.woff2 HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:10292 - "[1mGET /fonts/roboto/Roboto-Bold.woff2 HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:10292 - "[1mGET /chat/getTipNames HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ('127.0.0.1', 10296) - "WebSocket /chat/ws" [accepted]
[32mINFO[0m:     connection open
[32mINFO[0m:     127.0.0.1:10292 - "[1mGET /static/Bing.png HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10294 - "[1mGET /static/Background.jpg HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:10292 - "[1mGET /fonts/roboto/Roboto-Regular.woff HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:10293 - "[1mGET /fonts/roboto/Roboto-Medium.woff HTTP/1.1[0m" [31m404 Not Found[0m
[32mINFO[0m:     127.0.0.1:10291 - "[1mGET /fonts/roboto/Roboto-Bold.woff HTTP/1.1[0m" [31m404 Not Found[0m
Status code: 403

https://www.bing.com/turing/conversation/create
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\cors.py", line 75, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\fastapi\routing.py", line 324, in app
    await dependant.call(**values)
  File "D:\BaiduNetdiskDownload\Timeless-Sydney-main\main.py", line 62, in wsStream
    chatbot = await gpt.Chatbot.create(cookies = json.loads(open('./config/cookie.json', 'r', encoding='utf-8').read()))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 42, in create
    await Conversation.create(self.proxy, cookies=cookies),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cheng\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\conversation.py", line 112, in create
    raise Exception("Authentication failed")
Exception: Authentication failed
[32mINFO[0m:     connection closed
[32mINFO[0m:     127.0.0.1:10294 - "[1mGET /static/User.png HTTP/1.1[0m" [32m200 OK[0m

**Comment by xbzstudio** [comment]
不是404的问题，那几个文件404是正常的，因为mdui和angular需要另外的文件而我没有给他们准备好（但是也能正常工作）

你的问题是属于梯子问题，可以尝试换个节点或者换个梯子，建议使用我推荐的geph，很多人都是这个问题用了geph解决了（geph是免费vpn）
